# Advanced Numpy (reshape , concatenate, splitting , hsplit etc)

In [12]:
import numpy as np
from scipy import stats

arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
reshaped_3d_arr = arr.reshape(2, 2, 3)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concat_arr = np.concatenate((arr1, arr2), axis=0)

arr3 = np.array([[7], [8]])
concat_arr_col = np.concatenate((arr1, arr3), axis=1)

arr = np.arange(9).reshape(3, 3)
split_arr = np.split(arr, 3, axis=0)
split_arr_col = np.split(arr, 3, axis=1)

hsplit_arr = np.hsplit(arr, 3)
vsplit_arr = np.vsplit(arr, 3)

arr = np.array([[1, 2, 3], [4, 5, 6]])
appended_arr = np.append(arr, [[7, 8, 9]], axis=0)
appended_arr_col = np.append(arr, [[7], [8]], axis=1)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstack_arr = np.hstack((arr1, arr2))
vstack_arr = np.vstack((arr1, arr2))
print(vstack_arr)
arr = np.array([[[1], [2], [3]]])
squeezed_arr = np.squeeze(arr)
print(squeezed_arr)
arr = np.array([1, 2, 3])
expanded_arr = np.expand_dims(arr, axis=0)
expanded_arr_1 = np.expand_dims(arr, axis=1)
print(expanded_arr)
print(expanded_arr_1)
arr = np.array([[1, 2], [3, 4]])
flattened_arr_ravel = np.ravel(arr)
flattened_arr_flatten = arr.flatten()
print(flattened_arr_flatten)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]
[1 2 3 4]
